### PR TITLE
changes for GUI for diagnostics code rework

### PR DESCRIPTION
**Pull request by isubsmith**
This looks much better....

Anyway, changes for UVCDAT GUI for the reworking of uvcmetrics.

### CODE REVIEW

**Comment by doutriaux1** [comment]
@painter1 @isubsmith do we need this for 2.2 release?

**Comment by isubsmith** [comment]
diagnostics in the GUI are completely broken with a uvcmetrics tag > 2.1
(to the point of syntax errors stopping uvcdat initialization I suspect)

Lots of features and code improvements have been enabled in uvcmetrics
since tag 2.1

the code is fairly self-contained (only affects the diagnostics subpanel in
uvcdat GUI)

I would suggest it is fairly low risk to uvcdat and fairly substantial
changes in diagnostics, so yes, I think it needs to make the 2.2 release.

NOTE: I still need to move the uvcmetrics 2.2 tag slightly to pick up some
co-related changes there. I'm waiting to hear from Jeff or Jim on if I
should tag off of devel/ or master/ though in uvcmetrics.

On Mon, Mar 2, 2015 at 10:24 AM, Charles Doutriaux <notifications@github.com

**Comment by doutriaux1** [comment]
@isubsmith @painter1 let's talk about the 2.2 tag point during today's 10am meeting.

**Comment by painter1** [comment]
Yes, this is essential for the next release.  Something major broke which worked before.  And sticking with 2.1 is unsatisfactory because we have improvements which have to get out, such as new plot sets and better performance.

**Comment by aashish24** [comment]
@painter1 please approve

**Pull request merged**
