### PR TITLE
Issues for 911 in colormap editor fixed

### LINKED ISSUE #911: UI problems on colormap editor
Some issues remain after UV-CDAT/VisTrails#1

@williams13 [said](https://github.com/UV-CDAT/VisTrails/pull/1#issuecomment-62959341):

> @remram44 can we change the colormap GUI slightly? At the bottom of the GUI it has the "Cancel", and "OK" buttons. Should there be an "Apply" button? The "Apply" and "OK" buttons should behave the same except that the "Apply" button will not remove the GUI.
> 
> The selection of the colormap index buttons are slow to appear when you first bring up the colormap. The index buttons from (0 to 255) should be not be buttons. This causes slowness in the generation of the colormap.
> 
> The index buttons from 240 to 255 (the bottom row) are missing.
> 
> Selection of the indexes seems a bit off. When selecting more than on index button, it looks as if there's another index colormap in the back.

@remram44 [said](https://github.com/UV-CDAT/VisTrails/pull/1#issuecomment-62589949):

> Ok this happened while I was editing colors:  
> 
> 
> Also, when the "default" map is selected, both "ok" and "cancel" buttons are disabled:  
>

### PR DESCRIPTION
**Pull request by vvpalav**
Please Merge and Test

Fixes UV-CDAT/uvcdat#911

### CODE REVIEW

**Comment by remram44** [comment]
(I ran clean up from my IDE, same branch)

If I select a different colormap (than default) and close/reopen the editor, "default" is selected but the buttons are not disabled.

Unrelated, I get an Attribute error when shutting down (gui/uvcdat/esgf.py line 950), and a blue "search" button has appeared in the "add variable" window (which doesn't seem to work).

**Comment by remram44** [comment]
After your changes, I can still reproduce the issue I had:

**Comment by vvpalav** [comment]
@remram44 can you please provide steps to recreate?

**Comment by remram44** [comment]
I just click on some buttons at the bottom, change a couple of colors, it usually happens right away.

**Comment by doutriaux1** [comment]
@remram44 are on Linux or Mac. I tested this yesterday as well on mac. I used to see it but didn't yesterday. I will test on Linux now.

**Comment by remram44** [comment]
My exact steps: http://imgur.com/a/yWm8l/

Might be a VM glitch if no one can reproduce. I can try on native OSX tonight.

**Comment by doutriaux1** [comment]
you're on Linux. Need to try there. If i remeber correctly this is built on top of native window color dialog. For example on my mac the blend button is not at the same place as on your screenshots. see bellow

**Comment by doutriaux1** [comment]
colormapeditor

**Comment by vvpalav** [comment]
I tested it again, its working fine on mac os and buttons are rearranging due to QDialogButtonBox.
About Apply and other buttons enabled for default on cancel/reopen, constructor is not getting called when we reopen colormap editor window. Any suggestions on this would be helpful.

**Comment by vvpalav** [comment]
I just fixed issue mentioned by @remram44 about selecting - different colormap (than default) and cancel/close/reopen the editor, "default" is selected but the buttons are not disabled.
Branch name is -- uvcdat-911-extended_issue_with_default_colormap

**Pull request merged**
