### PR TITLE
Fixes opendap connections

### PR DESCRIPTION
**Pull request by chaosphere2112**
These changes make it so the user's `.dodsrc` file is properly set up to use OpenDAP to retrieve data from ESGF. I was able to get files off of Oakridge's system, using both a direct OpenDAP URL as well as searching and browsing for data.

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@doutriaux1 @aashish24

**Comment by chaosphere2112** [comment]
@doutriaux1 Ping

**Comment by doutriaux1** [comment]
@chaosphere2112 @aashish24 let's not forget to retag uvcdat-2.4.0 on vistrails repo

**Comment by aashish24** [comment]
> @chaosphere2112 @aashish24 let's not forget to retag uvcdat-2.4.0 on vistrails repo

Roger that.

**Comment by chaosphere2112** [comment]
@aashish24 I did already

**Pull request merged**
