### PR TITLE
Removing the animation icon for 2.1

### PR DESCRIPTION
**Pull request by hgohil2805**
As per the discussions today, I have removed the 2D animation icon for 2.1. Please merge and test

### CODE REVIEW

**Comment by williams13** [comment]
when I do the following commands I am not getting the right response.
[naomi 15] ~/work/uvcdata/uvcdat > git fetch
[03:46 - 1.611.411.63]
[naomi 16] ~/work/uvcdata/uvcdat > git checkout uvcdat_removing_animation_icon
error: pathspec 'uvcdat_removing_animation_icon' did not match any file(s) known to git.
[03:46 - 1.441.381.62]

**Comment by vvpalav** [comment]
I think you need to be inside vistrails directory. 
/uvcdat/14-11-21/vistrails --> git remote -v
origin  https://github.com/UV-CDAT/VisTrails.git (fetch)
origin  https://github.com/UV-CDAT/VisTrails.git (push)

**Comment by williams13** [comment]
Verified that the incon has been removed.

**Comment by williams13** [comment]
Thanks. Just tested and Confirmed for merger.

**Pull request merged**
