### PR TITLE
Fix Gtype.

### PR DESCRIPTION
**Pull request by mcenerney1**

### CODE REVIEW

**Comment by remram44** [comment]
You really don't have to go through pull requests, if you're merging them immediately and not providing any kind of description...

**Comment by mcenerney1** [comment]
vcs only recognizes Taylordiagram as a legitimate presentation type.  This fix allows Taylor as an alternate.

**Comment by mcenerney1** [comment]
Thanks!!

**Comment by remram44** [comment]
Unless multiple people use the same account...? What is going on...

**Pull request merged**
