### PR TITLE
fix for @mcenerney1

### PR DESCRIPTION
**Pull request by doutriaux1**
@mcenerney1 was hitting a snag on that line
this helps him to keep going but
it needs further review by real GUI developers to make sure
it is a valid fix and not covering something more serious
@mcenerney1 if you could uncomment this in your code and post the original
error it would be great

### CODE REVIEW

**Comment by remram44** [comment]
A catch-all is obviously a bad idea. What is the error?

I'm strongly opposed to this.

**Comment by mcenerney1** [comment]
I don't know exactly what was commented out.

**Comment by doutriaux1** [comment]
@mcenerney1 just look at the file change (on github, follow link if you read this in your email)

**Comment by isubsmith** [comment]
The change was to catch an exception around canvas=self.getCanvas() in vistrails/gui/uvcdat/plot.py.

Someone probably needs to remove the try:/except: and see what the original error was and fix that rather than catching the exception.

old code (in vistrails/gui/uvcdat/plot.py, line 54):
- canvas = self.getCanvas()

new code:
- try:
              + canvas = self.getCanvas()
              + except:
              + canvas = None

**Comment by doutriaux1** [comment]
@remram44 here's the original traceback:

```
Traceback (most recent call last):
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 660, in buttonClicked
    self.applyClicked()
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 777, in applyClicked
    self.displayCell(res30, row, col)
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/diagnosticsDockWidget.py", line 875, in displayCell
    projectController.plot_was_dropped(plotDropInfo)
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/project_controller.py", line 779, in plot_was_dropped
    self.check_update_cell(sheetName,row,col, update)
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/project_controller.py", line 913, in check_update_cell
    self.update_cell(sheetName, row, col, reuse_workflow)
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/project_controller.py", line 995, in update_cell
    reuse_workflow)
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/project_controller.py", line 1042, in update_workflow
    self.update_plot_configure(sheetName, row, column)
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/project_controller.py", line 850, in update_plot_configure
    plot_prop.set_controller(self)
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/plot.py", line 30, in set_controller
    self.updateProperties(None)
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/plot.py", line 54, in updateProperties
    canvas = self.getCanvas()
  File "/lgm/uvcdat/2015-03-20/vistrails/vistrails/gui/uvcdat/plot.py", line 72, in getCanvas
    return cellWidget.canvas
AttributeError: 'QPromptCellWidget' object has no attribute 'canvas'
```

**Comment by remram44** [comment]
Ok, `PlotProperties` gets updated too soon. This might rely on Qt signals happening synchronously. It needs to be fixed...

Something like this might be a good plan for 2.2 (then a real fix):

``` diff
--- a/vistrails/gui/uvcdat/plot.py
+++ b/vistrails/gui/uvcdat/plot.py
@@ -69,5 +69,5 @@ class PlotProperties(QtGui.QDockWidget):
         if sheetWidget is not None:
             cellWidget = sheetWidget.getCell(row, col)
-            if cellWidget is not None:
+            if cellWidget is not None and hasattr(cellWidget, 'canvas'):
                 return cellWidget.canvas
         return None
```

**Pull request merged**
