### PR TITLE
Hide 3D_Dual_Scalar plot

### PR DESCRIPTION
**Pull request by ThomasMaxwell**
Decided not to expose the dual scalar plot until next release- requires a ctest and some more tweaking.

### CODE REVIEW

**Comment by aashish24** [comment]
LGTM

**Comment by williams13** [comment]
Thanks… I’ll give it a try

**Comment by ThomasMaxwell** [comment]
This branch will not fix the the issue with dv3d.    As far as I know the vcs3D-fix_3d_plot_hanging branch still needs to be merged.

**Comment by williams13** [comment]
Okay, I’ll wait for Aashish!

Thanks for letting me know.

**Comment by ThomasMaxwell** [comment]
As I pointed out yesterday, the Hide_3D_Dual_Scalar branch will not fix the DV3D errors.

From: <Maxwell>, "Maxwell, Thomas P. (GSFC-606.2)[SCIENCE APPLICATIONS INTL CORP]" <thomas.maxwell@nasa.gov<mailto:thomas.maxwell@nasa.gov>>
Date: Wednesday, December 3, 2014 3:27 PM
To: UV-CDAT/VisTrails <reply@reply.github.com<mailto:reply@reply.github.com>>
Subject: Re: [VisTrails] Hide 3D_Dual_Scalar plot (#7)

This branch will not fix the the issue with dv3d.    As far as I know the vcs3D-fix_3d_plot_hanging branch still needs to be merged.

**Pull request merged**
