### PR TITLE
Send OSX profiler's stderr to log

### LINKED ISSUE #32: Redirection of errors is not going to the log file

### PR DESCRIPTION
**Pull request by remram44**
Fixes #32

Somebody should test that, didn't test it on OSX and don't know where this is used (this is dead code in VisTrails 2.1).

### CODE REVIEW

**Comment by vvpalav** [comment]
Just tested .. did not get any issues from #32 but got below warnings from QT

2015-03-31 10:17:50.589 Python[17776:289943] modalSession has been exited prematurely - check for a reentrant call to endModalSession:
2015-03-31 10:17:57.440 Python[17776:289943] modalSession has been exited prematurely - check for a reentrant call to endModalSession:

apparently it is a know bug on OS X for QT4: https://bugreports.qt.io/browse/QTBUG-37699

is this fine?

**Comment by vvpalav** [comment]
@doutriaux1 @williams13 @aashish24 .. can you guys test this as per your expectations?

**Comment by aashish24** [comment]
I don't think so. Why the redireftion not working for this error?

**Comment by aashish24** [comment]
@vvpalav if you are seering the warnings then it means that the issue is not fixed.

**Comment by remram44** [comment]
Did we ever have a redirection for non-Python errors?

**Comment by aashish24** [comment]
At one point David K was looking into it. I don't remember if we ever got the working. I am assuming that it should be possible but I could be wrong.

**Comment by remram44** [comment]
> At one point David K was looking into it. I don't remember if we ever got the working. I am assuming that it should be possible but I could be wrong.

I can find no trace of that. It is possible with e.g. `dup2()` but I strongly advise against it.

**Comment by remram44** [comment]
This is all of the `sys.stderr` redirections I did find though, as usual it's concerning:
- [vtUtilities.py](https://github.com/UV-CDAT/VisTrails/blob/cfb1bea2e42b06f0d2992b7ca789114d42470128/vistrails/packages/vtDV3D/vtUtilities.py#L90-L98) (I'm told this whole package is not used anymore)
- [commandLineWidget.py](https://github.com/UV-CDAT/VisTrails/blob/cfb1bea2e42b06f0d2992b7ca789114d42470128/vistrails/gui/uvcdat/commandLineWidget.py#L115-L118) (the calculator, bit us with UV-CDAT/uvcdat#1088)
- [shell.py](https://github.com/UV-CDAT/VisTrails/blob/cfb1bea2e42b06f0d2992b7ca789114d42470128/vistrails/gui/shell.py#L830-L832) (the VisTrails "console" window; only happens when that window is visible)
- [application.py](https://github.com/UV-CDAT/VisTrails/blob/cfb1bea2e42b06f0d2992b7ca789114d42470128/vistrails/core/application.py#L385) (the current redirection to the log file, unless `--output=` is used)

**Comment by aashish24** [comment]
okay, let's think more about this in the mean time I am merging this.

**Comment by vvpalav** [comment]
@aashish24 .. we discussed about this and we think It's not a good idea because if we ignore modal error from QT then redirecting other errors to log file would be like overlooking them unless someone actually open those log files for error check, which I think is rare. Some errors might be serious, needing immediate attention.

Still if you want this to be done then please just confirm once so that @remram44 can take necessary actions. Thank You.

**Comment by aashish24** [comment]
@vvpalav yes, we still want them to redirect. Showing messages on the console does not help. For instance, on windows, user won't even see it. On Linux and Mac, user cannot do anything about it and if they want to report, we ask then to send us the log file. If something critical happens, then the GUI should  display the message at the bottom panel or somewhere. 

If you want to show it, I would suggest, do two things:

1) redirect to log file
2) Show it in the gui (in some message panel but no pop up unless its critical)

Hope it makes sense. @williams13 please feel free to suggest your thoughts here.

**Comment by remram44** [comment]
But what kind of messages are you seeing, that do not come from Python?

If there are system messages from the GUI toolkit that add nothing to the log, I don't see a reason to add a hideous hack to hide them where every other application ever just keeps them there.

**Comment by remram44** [comment]
Filed UV-CDAT/uvcdat#1239, this is a merged pull request.

**Pull request merged**
