### PR TITLE
Uvcdat issues 830 682 681 save colormap show buttons

### PR DESCRIPTION
**Pull request by doutriaux1**
ok good repo now. Turns out when you do a pull request on github FROM UV-CDAT/VisTrails it still automatically makes a pull request to the original fork. Hence why the first pull request went to the wrong place.

### CODE REVIEW

**Comment by remram44** [comment]
Ok this happened while I was editing colors:

screenshot

Also, when the "default" map is selected, both "ok" and "cancel" buttons are disabled:

screenshot

**Comment by doutriaux1** [comment]
I don't know about the first error, you should probably file a issue for that one.
The second on is on purpose so that you cannot edit the default and get the error you complained about.
Feel free to improve before merging.

**Comment by williams13** [comment]
Can I checkout the bug fix for testing or has it been merged already?

[naomi 7] ~/work/uvcdata/uvcdat > git checkout uvcdat-issues-830-682-681-save-colormap-show-buttons
error: pathspec 'uvcdat-issues-830-682-681-save-colormap-show-buttons' did not match any file(s) known to git.
[12:47 - 0.940.750.60]

**Comment by remram44** [comment]
The branch still exists and hasn't been merged.

**Comment by williams13** [comment]
@remram44 can we change the colormap GUI slightly? At the bottom of the GUI it has the "Cancel", and "OK" buttons. Should there be an "Apply" button? The "Apply" and "OK" buttons should behave the same except that the "Apply" button will not remove the GUI. 

The selection of the colormap index buttons are slow to appear when you first bring up the colormap. The index buttons from (0 to 255) should be not be buttons. This causes slowness in the generation of the colormap. 

The index buttons from 240 to 255 (the bottom row) are missing. 

Selection of the indexes seems a bit off. When selecting more than on index button, it looks as if there's another index colormap in the back.

**Comment by doutriaux1** [comment]
@remram44 @vvpalav what is holding this pull? I'm filing a new issue for the bug that @remram44 sees.

**Comment by remram44** [comment]
This can be merged in as is. Moving the rest to a later milestone shouldn't cause major problems.

**Comment by williams13** [comment]
Hi Vinayak,

If Rémi is too busy, can you take a look at it and approve?

Thank and best regards,
Dean

**Comment by williams13** [comment]
Thanks Rémi… :-)

**Pull request merged**
