### PR TITLE
disable buttons at the bottom when colormap is default and editor is can...

### PR DESCRIPTION
**Pull request by vvpalav**
committing code for https://github.com/UV-CDAT/VisTrails/pull/4#issuecomment-64488001

### CODE REVIEW

**Comment by doutriaux1** [comment]
@remram44 can you please review and merge? I think it is probably moving the 2.1.0 tag once it's in. We had the code freeze last night but tags can still be moved for bug fixes until official release.

**Comment by remram44** [comment]
@vvpalav **I rebased the branch on top of the changes I had made last time, be carefull when fetching the branch** (use something like `git pull --rebase`)

I don't think `closeEvent()` is the right place to do that, for example if you click on the "colormap editor" action from the spreadsheet toolbar for a different cell, while the editor window is still open, it still resets to the default colormap without updating the buttons.

**Comment by vvpalav** [comment]
I just committed code again with showEvent implementation instead of closeEvent.
I have committed changes for https://github.com/UV-CDAT/uvcdat/issues/933 .. I did not create new pull request for 933.
Please verify and let me know if any issues

**Comment by remram44** [comment]
I had to rewrite and re-merge the whole thing...

This:

screen shot 2014-11-26 at 16 13 26

not ok :mask:

I recommend that you reset your repository _before_ making any other change, that sure is simpler than merging afterwards.

I will review when I can, but this doesn't look worth rewriting the 2.1 tags.

**Comment by remram44** [comment]
@vvpalav I still have the same issue I had with `closeEvent()`.

**Comment by vvpalav** [comment]
I just tested it .. its working fine in my machine. FYI .. I added showEvent function to handle this.
Can you please post screenshots or steps.
I also committed more code (Minor bug) at uvcdat-911-extended_issue_with_default_colormap
Can you please update and test again.

**Comment by remram44** [comment]
Here's what I just got on ddb60809: http://imgur.com/a/54T3X

**Comment by vvpalav** [comment]
@remram44 @doutriaux1 : committed code with some changes. Please merge and test.

Just removed customized handling for default colormap for 2.1, now buttons will be active for any colormap. If we still want this then may be we can raise new issue for 2.2
Technically earlier toolbar buttons (including Apply) were active for default, so we were only disabling Cancel for default. So I just removed this functionality and now all buttons are active. If someone tries to edit default then error message is already in place.

@williams13 .. I have also fixed screen size issue, Can you please test and paste screenshots if its not what expected.

**Comment by doutriaux1** [comment]
@vvpalav will that choke if you try to edit the default colormap. That was the reason it was disabled in the first place.

**Comment by vvpalav** [comment]
I tried it, got one dialog with error stating that default colormap cannot be edited. I can cook something better to prevent users doing this for later and as I said Apply was there on toolbar so it was actually never disabled. only cancel was disabled but its a least confusing button so keeping it alive won't hurt. 
I think changes are fine unless we find something else broken due to this.

**Comment by doutriaux1** [comment]
Yes but originally the apply icon wasn't visible, so you only really add the cancel/ok buttons. But @remram44 complained about getting an error message when editing default colormap see UV-CDAT/uvcdat#681

**Comment by doutriaux1** [comment]
I'm fine either way. @williams13 it's your call.

**Comment by remram44** [comment]
> Just removed customized handling for default colormap for 2.1, now buttons will be active for any colormap. If we still want this then may be we can raise new issue for 2.2

Are we giving up on fixing them?

**Comment by williams13** [comment]
Charles, I would like to discuss this with you in the morning before making the decision.

-Dean

**Comment by vvpalav** [comment]
@remram44 I can still fix those if its required. Only issue with default is when we edit it. So disabling all the buttons is not a good idea. Save/Blend/Reset/Apply needs to be alive for default too. So instead of disabling buttons we can find some other way to prevent users editing default colormap.

**Comment by williams13** [comment]
I checked out the colormap... It looks and behaves much better. Please merge.

**Pull request merged**
