### PR TITLE
fixes issues due to outline/outfill no being part of vcs anymore

### PR DESCRIPTION
**Pull request by doutriaux1**
@remram44 @vvpalav 
in the newer vcs we removed outline/outfill (deprecated) that led to errors while loading the GUI
This "seems" to fix it (the GUI loads again) but I can't really test sincethere is still the "inputPort" error that prevents plotting.

### CODE REVIEW

**Comment by remram44** [comment]
@vvpalav @hgohil2805 please review

**Comment by doutriaux1** [comment]
with @remram44 fix #16 it seems to work ok. But yes please @vvpalav and @hgohil2805 review and make sure I didn't yank anything vital.

**Comment by vvpalav** [comment]
seems okay I guess, I didn't get any error .. @doutriaux1 can you please merge and close this.

**Comment by doutriaux1** [comment]
All right thanks @vvpalav I'll take your green light!

**Pull request merged**
