### PR TITLE
Issue 1166, Removed VTK package from VisTrails GUI

### PR DESCRIPTION
**Pull request by vvpalav**
https://github.com/UV-CDAT/uvcdat/issues/1166 .. Please review and merge.

### CODE REVIEW

**Comment by remram44** [comment]
I'm rebasing this to get rid of your erroneous merge.

**Comment by remram44** [comment]
VTK packages is still used, e.g. from `vistrails/packages/uvcdat_cdms/init.py` L9:

``` python
from packages.vtk.vtkcell import QVTKWidget, QVTKWidgetToolBar, VTKCell
```

**Comment by vvpalav** [comment]
I tested after removing vtk and didn't get any error. Let me check more

**Comment by vvpalav** [comment]
I think it loads vtk library, so even if we don't load vtk package its working.

**Comment by vvpalav** [comment]
class QCDATWidget(QVTKWidget) & QVTKWidget.**init**(self, parent) .. VTK Widget is used in uvcdat_cdms QCDATWidget .. I am not sure if we remove that how will it behave .. I am doing testing, but didn't get any error yet.

**Comment by vvpalav** [comment]
.//vistrails/packages/ParaView/pvcell.py:3:from packages.vtk.vtkcell import QVTKWidget
.//vistrails/packages/pvclimate/pvgenericcell.py:8:from packages.vtk.vtkcell import QVTKWidget
.//vistrails/packages/uvcdat_cdms/init.py:9:from packages.vtk.vtkcell import QVTKWidget, QVTKWidgetToolBar, VTKCell
.//vistrails/packages/vtDV3D/CurtainPlotModule.py:12:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/DV3DCell.py:11:from packages.vtk.vtkcell import QVTKWidget, QVTKWidgetToolBar
.//vistrails/packages/vtDV3D/LevelSurfaceModule.py:11:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/MultiVolumeSlicerModule.py:14:#from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/ParallelCoordinatesModule.py:14:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VectorCutPlaneModule.py:16:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VectorVolumeModule.py:16:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VolumeRenderModule.py:11:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VolumeSlicerModule.py:14:from packages.vtk.base_module import vtkBaseModule
.//vistrails/packages/vtDV3D/VoxelizerModule.py:16:from packages.vtk.base_module import vtkBaseModule

In all found this many occurrences where something is imported from vtk package inside vistrails.
Mainly QVTKWidget is used to pass to constructor to several classes. 

Does anyone have any idea how to fix this?

**Comment by remram44** [comment]
Move the widget out?

**Comment by vvpalav** [comment]
Well .. I can try .. looking at all the imports ... we need to move out QVTKWidget, QVTKWidgetToolBar, VTKCell from packages.vtk.vtkcell and vtkBaseModule from packages.vtk.base_module.

Where do you want me to place this classes after moving them out from vtk?

**Comment by remram44** [comment]
You probably don't want to move VTKCell or vtkBaseModule...
I think it could go in uvcdat_cdms, unless I'm missing something.

**Comment by vvpalav** [comment]
I am going to put this new classes into Widget.py file .. unless you want me to create new python file for this?

**Comment by remram44** [comment]
This can't go in `widgets.py`. Could be `init.py`, or if too big a new file.

**Comment by vvpalav** [comment]
Alright, making changes.

**Comment by vvpalav** [comment]
pushed the changes. Please review and let me know if any issues.

**Comment by remram44** [comment]
Please learn how to use Git, I'm tired of removing nonsensical merges (2 here!) and unrelated changes from every branch.

**Comment by remram44** [comment]
Ok, I read your changes. I went and removed the code you commented out.

You had completely ignored the dependencies so I had to update that.

In addition to DV3D, there is still a dependency on the VTK package from [the QCDATWidget in uvcdat_cdms](https://github.com/UV-CDAT/VisTrails/blob/3e92adbe6ff095c1db29d2c155ba3b55a9d88ff3/vistrails/packages/uvcdat_cdms/init.py#L1470); the code is if-falsed-out, is it something we should remove? Apparently @doutriaux1 introduced it with d9dbdd34 (Jun 2014) and it was always commented out.

**Comment by doutriaux1** [comment]
Yes we can probably remove it safely. Probably left over from my expérimentations trying to get the widget ported to our vtk-based vcs.

**Comment by remram44** [comment]
Ready for merge, I guess; but I don't know much about your release cycle, that might not be safe for 2.2?

**Comment by vvpalav** [comment]
@doutriaux1 @aashish24 .. can we merge this for 2.2?

**Comment by aashish24** [comment]
thanks! I will have a look.

**Comment by aashish24** [comment]
@vvpalav sorry but I am getting merge conflicts now. It could be because of the recent changes that got merged before this branch. Could you please update it?

**Comment by aashish24** [comment]
@vvpalav I tried to resolve some of the conflicts but some other I don't quite understand. Sorry for delay in reviewing your branch.

**Comment by remram44** [comment]
There is no conflict.

**Comment by aashish24** [comment]
my bad. I got conflict during manual merge because I didn't have the full git history on my clone. LGTM :+1:

**Comment by aashish24** [comment]
One thing I noticed is that the load time speed up is still slow. Have you guys noticed it as well?

**Comment by remram44** [comment]
Should probably be profiled.

Python is not exactly fast to load up, and a lot of libs are still loaded at that time, but there might be unnecessary delays. I also remember that UV-CDAT does some HTTP requests at that time, which IMHO should definitely be taken off the critical path.

**Comment by doutriaux1** [comment]
@remram44 the http can be turned off if you choose not to send anonymous data. But I usually notice this affects more "closing time" (because it waits for the threads to end) rather than loading time.

**Comment by remram44** [comment]
(for anyone stumbling here: see UV-CDAT/uvcdat#1232)

**Comment by doutriaux1** [comment]
Thanks @remram44

**Pull request merged**
