### PR TITLE
Changes in support of plot set 11

### PR DESCRIPTION
**Pull request by mcenerney1**
Testing of plot set 3 failed to plot the data. This required additional changes to displayCell. Testing on 3, 4, 5, 11, and 12 were successful.

### CODE REVIEW

**Comment by mcenerney1** [comment]
@painter1 Check it out! Thanks.

**Comment by painter1** [comment]
LGTM - a good way to handle tuples of overlaid plots, plus some long-overdue coding improvements.
What plot sets have you tested on so far?

**Comment by mcenerney1** [comment]
Mostly 11 & 12 have been tested.  I'll try 3 and 5.  Of course only the gui is impacted.

**Comment by mcenerney1** [comment]
While testing #3, should the first plot have 2 curves: model and obs? If so, I have an issue.
What files, etc do you use on command line?

**Comment by painter1** [comment]
Yes, the first plot should have two curves, model and obs.  The second should have one curve, model-obs.  I usually test the GUI with NCEP obs and the cam35 model data, usually as climatologies.  My standard command-line test script is frontend/lotsa_diags.sh.  Here's what it has for atmosphere plot set 3:
diags --outputdir ~/tmp/diagout/ --model path=~/metrics_data/cam35_data/,climos=yes --obs path=/Users/painter1/metrics_data/obs_data_5.6/,filter="f_startswith('JRA25')",climos=yes --package AMWG --set 3 --var TREFHT --seasons ANN

**Comment by mcenerney1** [comment]
Jeff
Who actually does runs the pull request?  The changes that I pushed to the devel branch won't work until this is complete. 
Jim

**Comment by painter1** [comment]
```
Anybody can merge a pull request, but it should be another person. 
I would do it, but I'm waiting to hear that the change didn't break
anything else, in particular the heavily-used atmosphere plot sets 3
and 5.
- Jeff

On 5/19/15 11:10 AM, James McEnerney
  wrote:



  Jeff
    Who actually does runs the pull request? The changes that I
    pushed to the devel branch won't work until this is complete. 
    Jim
  —
    Reply to this email directly or view
      it on GitHub.
```

**Comment by painter1** [comment]
By "another person" I mean other than the person who submitted the request, i.e. not yourself.

**Comment by mcenerney1** [comment]
I did have a problem and subsequently repaired it. Testing on 3, 4, 5, 11, and 12 is now successful.

**Pull request merged**
