### PR TITLE
Reduce size

### PR DESCRIPTION
**Pull request by aashish24**

### CODE REVIEW

**Comment by aashish24** [comment]
@ThomasMaxwell @williams13 @remram44 please review. I need this asap for the release.

**Comment by remram44** [comment]
Seems pretty okay, except:
- I'm not entirely sure about the `vistrails/db/versions`. Might be safe to remove, but worth checking
- `vistrails/packages/vtDV3D` is still used in `vistrails/gui/uvcdat/variable.py` (see UV-CDAT/uvcdat#1056 and #17 discussion)

**Comment by remram44** [comment]
You should keep `vistrails/db/versions/v1_0_2` (current version); `v1_0_0` is also referenced through opm.

**Comment by aashish24** [comment]
I will update this request or may be someone else can push a new branch.

**Comment by remram44** [comment]
~~Rebase should wait for UV-CDAT/VisTrails#37~~

**Comment by doutriaux1** [comment]
@aashish24 ping

**Comment by aashish24** [comment]
@doutriaux1 I think we can close this one, since I don't think it makes sense knowing the new GUI is in development.

**Pull request closed without merging**
