### PR TITLE
Added labelskipdistance to isolines

### PR DESCRIPTION
**Pull request by chaosphere2112**
Adds isoline label spacing support to GUI

### CODE REVIEW

**Comment by chaosphere2112** [comment]
@aashish24

**Comment by chaosphere2112** [comment]
Solves UV-CDAT/uvcdat#1677

**Comment by aashish24** [comment]
thanks @chaosphere2112 !! this will make Jerry happy :smile: I am in the middle of anther PR review. I will get back to this later today.

**Comment by aashish24** [comment]
LGTM :+1:

**Pull request merged**
